const page = () => {
  return (
    <div className="max-w-[72rem] mx-auto px-3 mt-[90px]">
      <h2 className="text-[28px] font-[700] text-center mb-[22px] mt-[24px] xl:text-[36px] xl:mb-[35px] xl:mt-[35px]">
        Terms & Conditions
      </h2>
      <h2 className="text-[24px] font-[500] my-[8px] xl:text-[35px]">
        PLEASE READ THIS IMPORTANT DISCLAIMER CAREFULLY:
      </h2>
      <p>
        THE SERVICES ARE PROVIDED TO YOU AT YOUR OWN RISK. YOU ARE USING THE
        SERVICES FOR OBTAINING ASTROLOGICAL CONSULTATIONS ONLY. THE ASTROLOGY
        PARTNER MAY PROVIDE SUCH CONSULTATION BY USAGE OF VEDIC ASTROLOGY, TAROT
        READING, VAASTU, NUMEROLOGY, WESTERN ASTROLOGY OR ANY OTHER SUCH METHOD
        THAT MAY BE INFORMED TO YOU. YOU AGREE THAT ASTROLOGICAL CONSULTATION IS
        INHERENTLY SUBJECTIVE IN NATURE AND DIFFERENT ASTROLOGERS MAY ARRIVE AT
        VARYING OR EVEN CONFLICTING RESULTS, DESPITE FOLLOWING SIMILAR METHODS.
        THE COMPANY, ASTROLOGER PARTNERS AND THEIR RESPECTIVE AFFILIATES,
        OFFICERS, EMPLOYEES, AGENTS, PARTNERS AND LICENSORS HEREBY EXPRESSLY
        DISCLAIM ANY AND ALL WARRANTIES, ASSURANCES OR REPRESENTATIONS AS TO THE
        CORRECTNESS OR ACCURACY OF ANY ADVICE, PREDICTION OR REMEDY PROVIDED
        THROUGH THE SERVICES. YOU HEREBY AGREE AND ACKNOWLEDGE THAT THE SERVICES
        ARE NOT INTENDED AS A SUBSTITUTE FOR OR AS COMPLEMENTARY TO ACTUAL
        MEDICAL, LEGAL OR OTHER SUCH PROFESSIONAL ADVICE THAT YOU MAY OBTAIN.
      </p>
    </div>
  );
};

export default page;
