import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Mainfooter from "@/components/Footer/Mainfooter";
import Header from "@/components/header/Header";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const loginToken = cookieStore.get("loginToken");
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header loginToken={loginToken?.value} />
        {children}
        <Mainfooter />
      </body>
    </html>
  );
}
